export enum TableNames {
  DELIVERY_POINT = 'DELIVERY_POINT',
  AUTHOR = 'AUTHOR',
  GENRE = 'GENRE',
  LANGUAGE = 'LANGUAGE',
  PUBLISHER = 'PUBLISHER',
  BOOK = 'BOOK',
  PRODUCT = 'PRODUCT',
  DISCOUNT = 'DISCOUNT',
  CATEGORY = 'CATEGORY',
}
