export enum AppRoutes {
  MAIN = 'main',
  ADMIN = 'admin',
  BOOKS = 'books',
  PRODUCTS = 'products',
  DISCOUNTS = 'discounts',
  DELIVERY = 'delivery',
  CATEGORIES = 'categories',
  PRODUCT = 'product',
  SEARCH = 'search',
  CART = 'cart',
  ORDER_TRACKER = 'order-tracker',
  ORDERS = 'orders',
  AUTH = 'auth',
  LOGIN = 'login',
  SERVICE_UNAVAILABLE = 'service-unavailable',
  ERROR = 'error',
}
