export enum ApiQueryParams {
  LANGS = 'langs',
  GENRES = 'genres',
  AUTHORS = 'authors',
  PUBLISHER = 'publishers',
  YEAR_MIN = 'yearMin',
  YEAR_MAX = 'yearMax',
  ID = 'id',
  COUNT = 'count',
  PAGE = 'page',
  PER_PAGE = 'perPage',
  TEXT = 'text',
  CATEGORIES = 'categories',
  TRACK = 'track',
  TAKE = 'take',
}
