export enum ApiControlles {
  ROOT = '/',
  BOOKS = '/books',
  MAIN = '/main',
  AUTHORS = '/authors',
  GENRES = '/genres',
  CREATE = '/create',
  PUBLISHERS = '/publishers',
  LANGUAGES = '/languages',
  PRODUCTS = '/products',
  TOGGLE_SALES_STATE = '/toggle_sales_state',
  DISCOUNTS = '/discounts',
  ADD = '/add',
  DELIVERY = '/delivery',
  TOGGLE_STATE = 'toggle_state',
  CATEGORIES = '/categories',
  SIMILAR = '/similar',
  SEARCH = '/search',
  ORDERS = '/orders',
  CHANGE_STATE = '/change_state',
  BY_TRACK = '/by_track',
  USER = '/user',
  LOGIN = '/login',
  LOGOUT = '/logout',
}
